"""Remove unused columns

Revision ID: 24ca55348f73
Revises: 
Create Date: 2025-01-07 22:10:57.259601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ca55348f73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('actual_severity')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('actual_severity', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
